name: ✨ Main workflow
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    name: Courses
    uses: ./.github/workflows/deploy_course.yaml
    secrets: inherit
